version: '3.4'

services:
  catalogdb:
    image: mongo

  customerdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  customer.api:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: Services/Customer/Customer.API/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:
