version: '3.4'

services:
  mongodb:
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
        - mongo_data:/data/db

  postgresdb:
    container_name: postgresdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@domain.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mongodb:27017"
    depends_on:
      - mongodb
    ports:
      - "8000:80"

  customer.api:
    container_name: customer.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=postgresdb;Port=5432;Database=CustomerDB;User Id=admin;Password=admin1234;"
    depends_on:
      - postgresdb
    ports:
      - "8001:80"


  order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=postgresdb;Port=5432;Database=OrderDB;User Id=admin;Password=admin1234;"
    depends_on:
      - postgresdb
    ports:
      - "8002:80"

